name: CI/CD Pipeline
on:
    push:
        branches: [main, staging]
    release:
        types: [created]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: pytest

    deploy-staging:
        needs: build-test
        if: github.ref == 'refs/heads/staging'
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Staging
                run: echo "Deploying to staging..."
                env:
                    STAGING_SECRET: ${{ secrets.STAGING_SECRET }}

    deploy-production:
        needs: build-test
        if: github.event_name == 'release'
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Production
                run: echo "Deploying to production..."
                env:
                    PROD_SECRET: ${{ secrets.PROD_SECRET }}
