name: CI/CD Pipeline
on:
    push:
        branches: [main, staging]
    release:
        types: [created]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: pytest

    deploy-staging:
        needs: build-test
        if: github.ref_name == 'staging'
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Staging
              env:
                STAGING_SECRET: ${{ secrets.STAGING_SECRET }}
              run: |
                echo "Deploying to staging..."
                # Deploy to production only on release creation
                nohup python app.py deploy --env staging & 
                echo "Staging deployment complete."


    deploy-production:
        needs: build-test
        if: github.ref_name == 'main'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Deploy to Production
              env:
                PROD_SECRET: ${{ secrets.PROD_SECRET }}
              run: |
                echo "Deploying to production..."
                cd ${{ github.workspace }}
                # Ensure the app is ready for production
                pwd
                ls -la
                # Deploy to production only on release creation
                nohup python app.py deploy --env production &
                echo "Production deployment complete."
    
