name: CI/CD Pipeline

on:
  push:
    branches: [main, staging]
  release:
    types: [created]

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: pytest

  deploy-staging:
    needs: build-test
    if: github.ref_name == 'staging'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-54-188-9-224.us-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Staging Deploy and Setup EC2
        run: |
          ssh ubuntu@ec2-54-188-9-224.us-west-2.compute.amazonaws.com << 'EOF'
            set -e
            echo "============================================="
            echo "Updating system packages..."
            echo "============================================="
            sudo apt update && sudo apt install -y python3 python3-pip git curl build-essential

            echo "Entering project directory..."
            
            cd ~/flask-app
            git checkout -b staging
            git pull origin/staging
            echo "============================================="
            echo "Setting up Python environment..."
            echo "============================================="
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            echo "============================================="
            echo "Stopping Gunicorn if running..."
            echo "============================================="
            pkill gunicorn || true
            echo "============================================="
            echo " Checking if app is down before restart..."
            echo "============================================="
            if ! curl --silent --fail http://localhost:6000/; then
              echo " App not reachable. Safe to restart."
            else
              echo "App still reachable, continuing deployment anyway."
            fi
            echo "============================================="
            echo "Starting Gunicorn..."
            echo "============================================="
            nohup venv/bin/gunicorn app:app --bind 0.0.0.0:6000 > logs.txt 2>&1 &

            echo " Waiting for app to start..."
            sleep 5
            echo "============================================="
            echo "Health check:"
            echo "============================================="

            curl --fail http://localhost:6000/ || echo "App not responding"

            echo "============================================="
            echo " Last 10 lines of log:"
            echo "============================================="
            tail -n 10 logs.txt || echo "No logs found."
          EOF
        env:
          STAGING_SECRET: ${{ secrets.STAGING_SECRET }}

  deploy-production:
    needs: build-test
    if: github.ref_name == 'main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-54-188-9-224.us-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy and Setup EC2
        run: |
          ssh ubuntu@ec2-54-188-9-224.us-west-2.compute.amazonaws.com << 'EOF'
            set -e
            echo "============================================="
            echo "Updating system packages..."
            echo "============================================="
            sudo apt update && sudo apt install -y python3 python3-pip git curl build-essential

            echo "Entering project directory..."
            
            cd ~/flask-app
            git pull
            echo "============================================="
            echo "Setting up Python environment..."
            echo "============================================="
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            echo "============================================="
            echo "Stopping Gunicorn if running..."
            echo "============================================="
            pkill gunicorn || true
            echo "============================================="
            echo " Checking if app is down before restart..."
            echo "============================================="
            if ! curl --silent --fail http://localhost:5000/; then
              echo " App not reachable. Safe to restart."
            else
              echo "App still reachable, continuing deployment anyway."
            fi
            echo "============================================="
            echo "Starting Gunicorn..."
            echo "============================================="
            nohup venv/bin/gunicorn app:app --bind 0.0.0.0:5000 > logs.txt 2>&1 &

            echo " Waiting for app to start..."
            sleep 5
            echo "============================================="
            echo "Health check:"
            echo "============================================="

            curl --fail http://localhost:5000/ || echo "App not responding"

            echo "============================================="
            echo " Last 10 lines of log:"
            echo "============================================="
            tail -n 10 logs.txt || echo "No logs found."
          EOF
        env:
          PROD_SECRET: ${{ secrets.PROD_SECRET }}
