name: CI/CD Pipeline

on:
  push:
    branches: [main, staging]
  release:
    types: [created]

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: pytest

  deploy-staging:
    needs: build-test
    if: github.ref_name == 'staging' && github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - name: Deploy to Staging
        env:
          STAGING_SECRET: ${{ secrets.STAGING_SECRET }}
        run: |
          echo "Deploying to staging..."
          nohup python app.py deploy --env staging &
          echo "Staging deployment complete."

  deploy-production:
    needs: build-test
    if: github.ref_name == 'main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-34-220-116-134.us-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@ec2-34-220-116-134.us-west-2.compute.amazonaws.com << 'EOF'
            pip install -r requirements.txt
            sleep 5
            nohup python app.py deploy --env production &
            cat nohup,out
            echo "App deployed on EC2"
          EOF
